import type { AppId, AppMeta } from '@/os/types'
import { HOME } from '@/store/fs'

import Files from './Files'
import Terminal from './terminal/Terminal'
import Browser from './Browser'
import Music from './Music'
import SystemMonitor from './SystemMonitor'
import SettingsApp from './SettingsApp'
import Trash from './Trash'
import Projects from './Projects'
import Editor from './Editor'
import ResumeViewer from './ResumeViewer'
import Skills from './Skills'
import TechStack from './TechStack'
import Contact from './Contact'
import Experience from './Experience'
import { Calculator, Calendar, Notes } from './Accessories'
import Stations from './Stations'
import SecurityLab from './SecurityLab'
import WebSecurity from './WebSecurity'
import AiSecurity from './AiSecurity'
import Network from './Network'
import Knowledge from './Knowledge'
import GitHub from './GitHub'
import Services from './Services'
import Testimonials from './Testimonials'

/**
 * Every application in the OS. Order here is the order they appear in the
 * launcher and (for `inDock` entries) the dock.
 */
export const apps: AppMeta[] = [
  // --- Portfolio ----------------------------------------------------------
  {
    id: 'stations',
    name: 'Workspace',
    title: 'Workspace — Stations',
    glyph: '🧭',
    accent: '#f59e0b',
    description: 'Every bench in the workspace, and the way into each',
    component: Stations,
    defaultSize: { w: 900, h: 640 },
    minSize: { w: 420, h: 380 },
    singleInstance: true,
    onDesktop: true,
    inDock: true,
    category: 'Portfolio',
  },
  {
    id: 'projects',
    name: 'Projects',
    title: 'Project Manager',
    glyph: '📁',
    accent: '#f59e0b',
    description: 'Case studies for the things I have built',
    component: Projects,
    defaultSize: { w: 940, h: 640 },
    minSize: { w: 520, h: 380 },
    singleInstance: true,
    onDesktop: true,
    inDock: true,
    category: 'Portfolio',
  },
  {
    id: 'about',
    name: 'About Me',
    title: 'About.md — Text Editor',
    glyph: '📝',
    accent: '#38bdf8',
    description: 'The long version, as a Markdown document',
    component: Editor,
    defaultProps: { path: `${HOME}/About.md` },
    defaultSize: { w: 720, h: 620 },
    singleInstance: true,
    onDesktop: true,
    category: 'Portfolio',
  },
  {
    id: 'resume',
    name: 'Resume',
    title: 'Resume — Document Viewer',
    glyph: '📄',
    accent: '#f87171',
    description: 'Résumé, viewable and downloadable',
    component: ResumeViewer,
    defaultSize: { w: 860, h: 720 },
    singleInstance: true,
    onDesktop: true,
    inDock: true,
    category: 'Portfolio',
  },
  {
    id: 'skills',
    name: 'Skills',
    title: 'skillpkg — Package Manager',
    glyph: '📦',
    accent: '#34d399',
    description: 'Every skill, installed and versioned',
    component: Skills,
    defaultSize: { w: 820, h: 600 },
    singleInstance: true,
    onDesktop: true,
    category: 'Portfolio',
  },
  {
    id: 'experience',
    name: 'Experience',
    title: 'Timeline',
    glyph: '🗓️',
    accent: '#a78bfa',
    description: 'Where I have worked and what I did there',
    component: Experience,
    defaultSize: { w: 800, h: 640 },
    singleInstance: true,
    onDesktop: true,
    category: 'Portfolio',
  },
  {
    id: 'techstack',
    name: 'Tech Stack',
    title: 'Software Center',
    glyph: '🧰',
    accent: '#22d3ee',
    description: 'The tools I actually reach for',
    component: TechStack,
    defaultSize: { w: 880, h: 620 },
    singleInstance: true,
    onDesktop: true,
    category: 'Portfolio',
  },
  {
    id: 'contact',
    name: 'Contact',
    title: 'Compose — Mail',
    glyph: '✉️',
    accent: '#fb7185',
    description: 'Send a message without leaving the desktop',
    component: Contact,
    defaultSize: { w: 800, h: 620 },
    singleInstance: true,
    onDesktop: true,
    inDock: true,
    category: 'Portfolio',
  },

  {
    id: 'github',
    name: 'GitHub',
    title: 'GitHub — Repositories',
    glyph: '🐙',
    accent: '#8b949e',
    description: 'Public repositories and activity, fetched live',
    component: GitHub,
    defaultSize: { w: 880, h: 660 },
    minSize: { w: 440, h: 380 },
    singleInstance: true,
    onDesktop: true,
    inDock: true,
    category: 'Portfolio',
  },
  {
    id: 'services',
    name: 'Services',
    title: 'Services',
    glyph: '🧾',
    accent: '#39ace1',
    description: 'What I can be hired to build',
    component: Services,
    defaultSize: { w: 860, h: 620 },
    minSize: { w: 420, h: 380 },
    singleInstance: true,
    onDesktop: true,
    category: 'Portfolio',
  },
  {
    id: 'testimonials',
    name: 'Testimonials',
    title: 'Testimonials',
    glyph: '💬',
    accent: '#fbbf24',
    description: 'What people who have worked with me say',
    component: Testimonials,
    defaultSize: { w: 700, h: 580 },
    minSize: { w: 380, h: 360 },
    singleInstance: true,
    category: 'Portfolio',
  },

  // --- Security -----------------------------------------------------------
  {
    id: 'seclab',
    name: 'Security Lab',
    title: 'Security Lab',
    glyph: '🛡️',
    accent: '#f59e0b',
    description: 'Recon through reporting, and the tools used at each phase',
    component: SecurityLab,
    defaultSize: { w: 940, h: 660 },
    minSize: { w: 480, h: 380 },
    singleInstance: true,
    onDesktop: true,
    inDock: true,
    category: 'Security',
  },
  {
    id: 'websec',
    name: 'Web Security',
    title: 'Web Security — OWASP Top 10',
    glyph: '🌐',
    accent: '#a78bfa',
    description: 'How each OWASP category is tested for, and what removes it',
    component: WebSecurity,
    defaultSize: { w: 880, h: 660 },
    minSize: { w: 440, h: 380 },
    singleInstance: true,
    category: 'Security',
  },
  {
    id: 'aisec',
    name: 'AI Security',
    title: 'AI Security',
    glyph: '🧠',
    accent: '#34d399',
    description: 'Where model-backed applications break, and where the control sits',
    component: AiSecurity,
    defaultSize: { w: 880, h: 640 },
    minSize: { w: 440, h: 380 },
    singleInstance: true,
    category: 'Security',
  },
  {
    id: 'network',
    name: 'Network',
    title: 'Network — Topology',
    glyph: '🕸️',
    accent: '#22d3ee',
    description: 'An interactive lab topology, with protocols and ports',
    component: Network,
    defaultSize: { w: 920, h: 640 },
    minSize: { w: 440, h: 400 },
    singleInstance: true,
    category: 'Security',
  },
  {
    id: 'knowledge',
    name: 'Knowledge',
    title: 'Knowledge — Learning',
    glyph: '📚',
    accent: '#fcd34d',
    description: 'Current learning tracks and the methodologies behind them',
    component: Knowledge,
    defaultSize: { w: 820, h: 640 },
    minSize: { w: 420, h: 380 },
    singleInstance: true,
    category: 'Security',
  },

  // --- System & utilities -------------------------------------------------
  {
    id: 'files',
    name: 'Files',
    title: 'Files',
    glyph: '🗂️',
    accent: '#60a5fa',
    description: 'Browse the filesystem',
    component: Files,
    defaultProps: { path: HOME },
    defaultSize: { w: 900, h: 580 },
    minSize: { w: 520, h: 340 },
    onDesktop: true,
    inDock: true,
    category: 'System',
  },
  {
    id: 'terminal',
    name: 'Terminal',
    title: 'Terminal',
    glyph: '❯',
    accent: '#4ade80',
    description: 'A shell that actually runs commands',
    component: Terminal,
    defaultSize: { w: 780, h: 480 },
    minSize: { w: 420, h: 240 },
    onDesktop: true,
    inDock: true,
    category: 'System',
  },
  {
    id: 'browser',
    name: 'Browser',
    title: 'Browser',
    glyph: '🌐',
    accent: '#818cf8',
    description: 'Tabs, bookmarks and history',
    component: Browser,
    defaultSize: { w: 980, h: 680 },
    minSize: { w: 520, h: 380 },
    onDesktop: true,
    inDock: true,
    category: 'Internet',
  },
  {
    id: 'monitor',
    name: 'System Monitor',
    title: 'System Monitor',
    glyph: '📊',
    accent: '#f472b6',
    description: 'Live resources, processes and career stats',
    component: SystemMonitor,
    defaultSize: { w: 780, h: 600 },
    singleInstance: true,
    inDock: true,
    category: 'System',
  },
  {
    id: 'settings',
    name: 'Settings',
    title: 'Settings',
    glyph: '⚙️',
    accent: '#94a3b8',
    description: 'Wallpaper, theme, sound and session',
    component: SettingsApp,
    defaultSize: { w: 760, h: 580 },
    singleInstance: true,
    inDock: true,
    category: 'System',
  },
  {
    id: 'music',
    name: 'Music',
    title: 'Music',
    glyph: '🎵',
    accent: '#c084fc',
    description: 'Ambient tracks, synthesised in the browser',
    component: Music,
    defaultSize: { w: 460, h: 620 },
    minSize: { w: 380, h: 420 },
    singleInstance: true,
    inDock: true,
    category: 'Media',
  },
  {
    id: 'trash',
    name: 'Trash',
    title: 'Trash',
    glyph: '🗑️',
    accent: '#94a3b8',
    description: 'Deleted files, restorable',
    component: Trash,
    defaultSize: { w: 620, h: 460 },
    singleInstance: true,
    category: 'System',
  },
  {
    id: 'editor',
    name: 'Text Editor',
    title: 'Text Editor',
    glyph: '📝',
    accent: '#38bdf8',
    description: 'Read and edit files',
    component: Editor,
    defaultSize: { w: 720, h: 560 },
    hiddenFromLauncher: true,
    category: 'Accessories',
  },
  {
    id: 'calculator',
    name: 'Calculator',
    title: 'Calculator',
    glyph: '🧮',
    accent: '#fbbf24',
    description: 'Arithmetic, with keyboard support',
    component: Calculator,
    defaultSize: { w: 320, h: 480 },
    minSize: { w: 280, h: 420 },
    singleInstance: true,
    category: 'Accessories',
  },
  {
    id: 'calendar',
    name: 'Calendar',
    title: 'Calendar',
    glyph: '📅',
    accent: '#f87171',
    description: 'A month at a time',
    component: Calendar,
    defaultSize: { w: 420, h: 460 },
    singleInstance: true,
    category: 'Accessories',
  },
  {
    id: 'notes',
    name: 'Notes',
    title: 'Notes',
    glyph: '🗒️',
    accent: '#fcd34d',
    description: 'A scratchpad backed by a real file',
    component: Notes,
    defaultSize: { w: 520, h: 500 },
    singleInstance: true,
    category: 'Accessories',
  },
]

const byId = new Map<AppId, AppMeta>(apps.map((a) => [a.id, a]))

export function appById(id: AppId): AppMeta | undefined {
  return byId.get(id)
}

export const dockApps = apps.filter((a) => a.inDock)
export const desktopApps = apps.filter((a) => a.onDesktop)
export const launcherApps = apps.filter((a) => !a.hiddenFromLauncher)
